"""Broad NSE research universe (~400 names, large + mid + small). Invalid tickers get skipped
by data_loader. Survivorship caveat: this is a TODAY list, so delisted names are absent."""

EXTRA = """
360ONE AARTIIND ABB ABBOTINDIA ABCAPITAL ABFRL ACC ACE ADANIENSOL ADANIENT ADANIGREEN ADANIPORTS
ADANIPOWER AEGISLOG AFFLE AIAENG AJANTPHARM AKZOINDIA ALKEM ALKYLAMINE ALLCARGO ALOKINDS AMARAJABAT
AMBER AMBUJACEM ANANDRATHI ANGELONE APARINDS APLAPOLLO APLLTD APOLLOHOSP APOLLOTYRE APTUS ARE&M
ASAHIINDIA ASHOKLEY ASIANPAINT ASTERDM ASTRAL ATGL ATUL AUBANK AUROPHARMA AVANTIFEED AXISBANK
BAJAJ-AUTO BAJAJELEC BAJAJFINSV BAJAJHLDNG BAJFINANCE BALAMINES BALKRISIND BALRAMCHIN BANDHANBNK
BANKBARODA BANKINDIA BASF BATAINDIA BAYERCROP BDL BEL BEML BERGEPAINT BHARATFORG BHARTIARTL BHEL
BIKAJI BIOCON BIRLACORPN BLUEDART BLUESTARCO BOSCHLTD BRIGADE BRITANNIA BSE BSOFT CAMPUS CAMS
CANBK CANFINHOME CAPLIPOINT CARBORUNIV CASTROLIND CCL CDSL CEATLTD CENTRALBK CENTURYPLY CERA CESC
CGCL CGPOWER CHALET CHAMBLFERT CHEMPLASTS CHOLAFIN CHOLAHLDNG CIEINDIA CIPLA CLEAN COALINDIA COCHINSHIP
COFORGE COLPAL CONCOR COROMANDEL CRAFTSMAN CREDITACC CRISIL CROMPTON CSBBANK CUB CUMMINSIND CYIENT
DABUR DALBHARAT DATAPATTNS DBREALTY DCMSHRIRAM DEEPAKFERT DEEPAKNTR DELHIVERY DEVYANI DHANI DIVISLAB
DIXON DLF DMART DRREDDY ECLERX EICHERMOT EIDPARRY EIHOTEL ELECON ELGIEQUIP EMAMILTD ENDURANCE ENGINERSIN
EPL EQUITASBNK ERIS ESCORTS EXIDEIND FDC FEDERALBNK FINCABLES FINEORG FINPIPE FIVESTAR FLUOROCHEM
FORTIS FSL GAEL GAIL GALAXYSURF GARFIBRES GESHIP GICRE GILLETTE GLAND GLAXO GLENMARK GMDCLTD GMRINFRA
GNFC GODFRYPHLP GODREJAGRO GODREJCP GODREJIND GODREJPROP GRANULES GRAPHITE GRASIM GRAVITA GRINDWELL
GSFC GSPL GUJGASLTD HAL HAPPSTMNDS HATSUN HAVELLS HBLPOWER HCLTECH HDFCAMC HDFCBANK HDFCLIFE HEG
HEIDELBERG HEROMOTOCO HFCL HINDALCO HINDCOPPER HINDPETRO HINDUNILVR HINDZINC HOMEFIRST HONAUT HSCL
HUDCO ICICIBANK ICICIGI ICICIPRULI IDBI IDEA IDFCFIRSTB IEX IFBIND IGL IIFL INDHOTEL INDIACEM INDIAMART
INDIANB INDIGO INDUSINDBK INDUSTOWER INFIBEAM INFY INGERRAND INOXWIND INTELLECT IOB IOC IPCALAB IRB
IRCON IRCTC IRFC ISEC ITC ITI JAMNAAUTO JBCHEPHARM JBMA JINDALSAW JINDALSTEL JKCEMENT JKLAKSHMI JKPAPER
JKTYRE JMFINANCIL JSL JSWENERGY JSWINFRA JSWSTEEL JUBLFOOD JUBLINGREA JUBLPHARMA JUSTDIAL JWL JYOTHYLAB
KAJARIACER KALPATPOWR KALYANKJIL KANSAINER KARURVYSYA KAYNES KEC KEI KFINTECH KIMS KIRLOSBROS KIRLOSENG
KOTAKBANK KPIL KPITTECH KPRMILL KRBL KSB LALPATHLAB LAURUSLABS LAXMIMACH LICHSGFIN LICI LINDEINDIA
LODHA LT LTF LTIM LTTS LUPIN LXCHEM M&M M&MFIN MAHABANK MAHLIFE MAHSEAMLES MANAPPURAM MANKIND MAPMYINDIA
MARICO MARUTI MASTEK MAXHEALTH MAZDOCK MCX MEDANTA METROPOLIS MFSL MGL MHRIL MIDHANI MINDACORP MMTC
MOTHERSON MOTILALOFS MPHASIS MRF MRPL MSUMI MTARTECH MUTHOOTFIN NATCOPHARM NATIONALUM NAUKRI NAVINFLUOR
NAZARA NBCC NCC NESCO NESTLEIND NETWORK18 NEULANDLAB NEWGEN NH NHPC NIACL NILKAMAL NLCINDIA NMDC NOCIL
NTPC NUVOCO NYKAA OBEROIRLTY OFSS OIL OLECTRA ONGC ORIENTELEC PAGEIND PAISALO PATANJALI PAYTM PCBL
PEL PERSISTENT PETRONET PFC PFIZER PGHH PGHL PHOENIXLTD PIDILITIND PIIND PNB PNBHOUSING POLICYBZR
POLYCAB POLYMED POONAWALLA POWERGRID POWERINDIA PRAJIND PRESTIGE PRINCEPIPE PRSMJOHNSN PSB PVRINOX
QUESS RADICO RAILTEL RAIN RAINBOW RAJESHEXPO RALLIS RAMCOCEM RATNAMANI RAYMOND RBLBANK RCF RECLTD
REDINGTON RELAXO RELIANCE RENUKA RHIM RITES ROSSARI ROUTE RTNPOWER RVNL SAFARI SAIL SANOFI SAPPHIRE
SBFC SBICARD SBILIFE SBIN SCHAEFFLER SCHNEIDER SEQUENT SFL SHARDACROP SHILPAMED SHOPERSTOP SHREECEM
SHRIRAMFIN SHYAMMETL SIEMENS SIS SJVN SKFINDIA SOBHA SOLARINDS SONACOMS SONATSOFTW SPARC SPLPETRO
SRF STARHEALTH STLTECH SUDARSCHEM SUMICHEM SUNCLAYLTD SUNDARMFIN SUNDRMFAST SUNPHARMA SUNTECK SUNTV
SUPRAJIT SUPREMEIND SURYAROSNI SUVENPHAR SWANENERGY SWSOLAR SYMPHONY SYNGENE TANLA TATACHEM TATACOMM
TATACONSUM TATAELXSI TATAINVEST TATAMOTORS TATAPOWER TATASTEEL TATATECH TCI TCS TEAMLEASE TECHM TEGA
TEJASNET THERMAX THOMASCOOK TIINDIA TIMKEN TITAGARH TITAN TORNTPHARM TORNTPOWER TRENT TRIDENT TRITURBINE
TRIVENI TTKPRESTIG TTML TV18BRDCST TVSMOTOR UBL UCOBANK UJJIVANSFB ULTRACEMCO UNIONBANK UNOMINDA UPL
USHAMART UTIAMC VAIBHAVGBL VAKRANGEE VARROC VBL VEDL VENKEYS VESUVIUS VGUARD VINATIORGA VIPIND VOLTAS
VRLLOG VSTIND VTL WELCORP WELSPUNLIV WESTLIFE WHIRLPOOL WIPRO WOCKPHARMA YESBANK ZEEL ZENSARTECH
ZFCVINDIA ZYDUSLIFE
"""

UNIVERSE = sorted({f"{s}.NS" for s in EXTRA.split()})
if __name__ == "__main__":
    print(len(UNIVERSE))
